@baseUrl = http://localhost:8080

### Cadastrar Produto
POST {{baseUrl}}/produtos
Content-Type: application/json

{
  "categoriaId": 3,
  "nome": "Pastel de Pizza",
  "descricao": "Pastel com molho de tomate e queijo",
  "preco": 19.90,
  "disponivel": true,
  "tempoPreparoMinutos": 15
}

### Listar Produtos
GET {{baseUrl}}/produtos?page=0&size=10&sort=nome,asc

### Buscar produto por ID
GET {{baseUrl}}/produtos/1

### Atualizar Produto
PUT {{baseUrl}}/produtos/8
Content-Type: application/json

{
  "categoriaId": 2,
  "nome": "Pastel de Pizza",
  "descricao": "Pastel com molho de tomate e queijo",
  "preco": 19.90,
  "disponivel": true,
  "tempoPreparoMinutos": 15
}

### Excluir Produto
DELETE {{baseUrl}}/produtos/3

### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###